## Single page Tabular Scrape

- <a href="https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action">On this site</a>, scrape all the doctors info on page 292.
- Export the content into a CSV file called ```page_292.csv```.

In [1]:
## create cells as needed
import pandas as pd
import requests

In [2]:
url = "https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action?d-49653-p=292"

In [6]:
response = requests.get(url)
response.status_code

200

In [15]:
pd.read_html(response.text)[0]

,Physician Last Name,Physician First Name,Physician Middle Name,License Number,License Type,Effective Date,Date Updated,Year of Birth
0,Birdsong,Edward,M,164669,DO,03/26/2003,03/27/2003,1948.0
1,Lew,Mark,Bernard,133922,MD,03/26/2003,03/26/2003,1948.0
2,Han,Amy,Ching-Yu,181069,MD,03/26/2003,03/26/2003,1962.0
3,Chandrasekhar,Subramaniyam,NaN,221873,MD,03/26/2003,03/26/2003,1957.0
4,Etkin,Richard,H,137524,MD,03/25/2003,03/26/2003,1944.0
5,Care Medical,P.C.,NaN,None,NaN,03/25/2003,03/26/2003,NaN
6,Lawler,Paul,J,000490,PA,03/26/2003,03/26/2003,1948.0
7,Hartwright,Alva,James,204263,MD,03/21/2003,03/21/2003,1939.0
8,Kamau,Pius,Karu,140387,MD,03/21/2003,03/21/2003,1941.0
9,Peets,Shara,Kay,127942,MD,03/13/2003,03/14/2003,1945.0
10,Swersky,Steven,NaN,146497,MD,03/13/2003,03/14/2003,1951.0
11,Norman,Dianna,L,153061,MD,03/13/2003,03/14/2003,1952.0
12,Jackson,Oscar,F,140325,MD,03/19/2003,03/14/2003,1950.0
13,Bezabeh,Tsedaye,NaN,210226,MD,03/18/2003,03/12/2003,1962.0
14,Feldman,Jerome,H,143900,MD,03/17/2003,03/12/2003,1941.0
15,Waugh,Martin,Earl,176768,DO,04/16/2003,03/12/2003,1960.0
16,McClintock,John,S,182856,MD,03/17/2003,03/12/2003,1961.0
17,Juan,Felipe,Tanseco,115611,MD,03/18/2003,03/12/2003,1941.0
18,Hartin,Richard,NaN,148582,MD,03/07/2003,03/07/2003,1952.0
19,Kubski,George,NaN,130034,MD,03/07/2003,03/07/2003,1947.0
20,New Physician Search,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Physician Records \tvar css = "".visualping-con...",Physician Last Name Physician First Name Physi...,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
len(pd.read_html(response.text)[0])

22

In [19]:
df_singlepage = pd.read_html(response.text)[0]
df_singlepage

,Physician Last Name,Physician First Name,Physician Middle Name,License Number,License Type,Effective Date,Date Updated,Year of Birth
0,Birdsong,Edward,M,164669,DO,03/26/2003,03/27/2003,1948.0
1,Lew,Mark,Bernard,133922,MD,03/26/2003,03/26/2003,1948.0
2,Han,Amy,Ching-Yu,181069,MD,03/26/2003,03/26/2003,1962.0
3,Chandrasekhar,Subramaniyam,NaN,221873,MD,03/26/2003,03/26/2003,1957.0
4,Etkin,Richard,H,137524,MD,03/25/2003,03/26/2003,1944.0
5,Care Medical,P.C.,NaN,None,NaN,03/25/2003,03/26/2003,NaN
6,Lawler,Paul,J,000490,PA,03/26/2003,03/26/2003,1948.0
7,Hartwright,Alva,James,204263,MD,03/21/2003,03/21/2003,1939.0
8,Kamau,Pius,Karu,140387,MD,03/21/2003,03/21/2003,1941.0
9,Peets,Shara,Kay,127942,MD,03/13/2003,03/14/2003,1945.0
10,Swersky,Steven,NaN,146497,MD,03/13/2003,03/14/2003,1951.0
11,Norman,Dianna,L,153061,MD,03/13/2003,03/14/2003,1952.0
12,Jackson,Oscar,F,140325,MD,03/19/2003,03/14/2003,1950.0
13,Bezabeh,Tsedaye,NaN,210226,MD,03/18/2003,03/12/2003,1962.0
14,Feldman,Jerome,H,143900,MD,03/17/2003,03/12/2003,1941.0
15,Waugh,Martin,Earl,176768,DO,04/16/2003,03/12/2003,1960.0
16,McClintock,John,S,182856,MD,03/17/2003,03/12/2003,1961.0
17,Juan,Felipe,Tanseco,115611,MD,03/18/2003,03/12/2003,1941.0
18,Hartin,Richard,NaN,148582,MD,03/07/2003,03/07/2003,1952.0
19,Kubski,George,NaN,130034,MD,03/07/2003,03/07/2003,1947.0
20,New Physician Search,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Physician Records \tvar css = "".visualping-con...",Physician Last Name Physician First Name Physi...,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_singlepage.to_csv("page_292.csv", encoding = "UTF-8", index = False)

## Multipage Tabular Scrape

- <a href="https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AllRecordsAction.action">On this site</a>, scrape all doctors whose last names begin with "P".
- Export the content into a CSV file called ```md_P.csv```.

In [21]:
## create cells as needed
base_url = "https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p="

In [24]:
urls_lc = [(f"{base_url}{url_number}")for url_number in range (1,24)]

urls_lc

['https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=1',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=2',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=3',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=4',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=5',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=6',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=7',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=8',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=9',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=10',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=11',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=12',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=13',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=14',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=15',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=16',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=17',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=18',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=19',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=20',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=21',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=22',
 'https://apps.health.ny.gov/pubdoh/professionals/doctors/conduct/factions/AlphabetSearchAction.action?alpbhabetSearch=P*&d-49653-p=23']

In [22]:
from random import randrange
import time

In [ ]:
busted_links = []
df_all = []
total_links = len(urls_lc)
counter = 1 

for url in urls_lc:
    print(f"scraping {counter} of {total_links}")
    counter += 1
    response = requests.get(url)
    try:
        df = pd.read_html(response.text)[0]
    except:
        print(f"oh no! {url} returned {response.status_code}")
        busted_links.append(url)
    else:
        df_all.append(df)
        print(df)
    snoozer = randrange(30,45)
    print(f"snoozing for {snoozer} seconds before next scrape")
    time.sleep(snoozer)

print("done scraping all provided link")